title: "Kishen Senziani"
name: "Kishen Senziani"
description: "PhD student in Neuroscience"
url: "https://kishensenziani.github.io" # Ton url future
baseurl: "" 

# Tes informations personnelles basées sur ton CV
author:
  name: "Kishen Senziani"
  [cite_start]email: "kishen.senziani@eunige.ch" # [cite: 3]
  [cite_start]location: "Genève, Suisse" # [cite: 2]
  [cite_start]bio: "MSc Neuroscience & MSc Psychology | UNIGE" # [cite: 6, 27, 28]
  avatar: "assets/images/profile.png" # Tu devras uploader une photo nommée profile.png dans ce dossier
  twitter: "" # Ajoute si tu as
  google_scholar: "" # Ajoute si tu as
  github: "ton-pseudo-github"
  linkedin: "ton-pseudo-linkedin"
  researchgate: ""
  [cite_start]orcid: "0000-0003-2051-4562" # [cite: 4]

# Menu de navigation
nav:
  - title: "Home"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "Resume"
    url: /resume/
  - title: "Talks & Posters"
    url: /talks/
  - title: "Teaching"
    url: /teaching/

# Pied de page
footer:
  copyright: "Kishen Senziani"
